import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import { LayoutProvider } from "@/context/LayoutContext";
import Layout from "@/layout/Layout";
import { LoaderProvider } from "@/context/LoaderContext";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
};

const clientId: string | undefined = process.env.NEXT_PUBLIC_OAUTH_CLIENT_ID;
if (!process.env.NEXT_PUBLIC_OAUTH_CLIENT_ID) {
  throw new Error("NEXT_PUBLIC_OAUTH_CLIENT_ID is not defined");
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={clientId || ""}>
        <LoaderProvider>
          <AuthProvider>
            <LayoutProvider>
              <Toaster position="top-right" duration={3000} richColors />
              <Layout>{children}</Layout>
            </LayoutProvider>
          </AuthProvider>
        </LoaderProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
