"use client";
import { useLayout } from "@/context/LayoutContext";
import { Metadata } from "next";
import { useEffect } from "react";

export default function Home() {
  const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
  };
  const { setShowHeader } = useLayout();

  useEffect(() => {
    setShowHeader(true);
    return () => {
      setShowHeader(false);
    }
  }, [])
  return (
    <div>Home</div>
  );
}
