import { Metadata } from "next";

export default function Home() {
  const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
  };
  return (
    <div>Home</div>
  );
}
